import { useState, useCallback } from 'react';
import { TuneSettings, DriveType, TuneType, tuneTypeDescriptions, UnitSystem, convertTuneToUnits, getUnitLabels } from '@/lib/tuningCalculator';
import { TuningModule, ModuleCategory } from './TuningModule';
import { BlueprintSlider } from './BlueprintSlider';
import { EngineeringTable, FrontRearValue, CompactValue } from './EngineeringTable';
import { Button } from '@/components/ui/button';
import { Copy, Check, Gauge, Settings2, Wind, Disc, Cog, Wrench, Compass, Activity } from 'lucide-react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

interface BlueprintTunePanelProps {
  tune: TuneSettings;
  driveType: DriveType;
  tuneType: TuneType;
  unitSystem: UnitSystem;
  carName?: string;
}

export const BlueprintTunePanel = ({ 
  tune, 
  driveType, 
  tuneType, 
  unitSystem, 
  carName 
}: BlueprintTunePanelProps) => {
  const [copied, setCopied] = useState(false);
  const [draggedModule, setDraggedModule] = useState<string | null>(null);
  
  const tuneInfo = tuneTypeDescriptions[tuneType];
  const displayTune = convertTuneToUnits(tune, unitSystem);
  const units = getUnitLabels(unitSystem);

  const formatTuneForClipboard = () => {
    const lines = [
      `═══════════════════════════════════`,
      `🏎️ ${carName || 'Custom Car'} - ${tuneInfo.title} Tune`,
      `═══════════════════════════════════`,
      ``,
      `▸ TIRE PRESSURE`,
      `  Front: ${displayTune.tirePressureFront} ${units.pressure}`,
      `  Rear: ${displayTune.tirePressureRear} ${units.pressure}`,
      ``,
      `▸ GEARING`,
      `  Final Drive: ${tune.finalDrive.toFixed(2)}`,
    ];

    if (tune.gearRatios && tune.gearRatios.length > 0) {
      tune.gearRatios.forEach((ratio, i) => {
        const gearName = i === 0 ? '1st' : i === 1 ? '2nd' : i === 2 ? '3rd' : `${i + 1}th`;
        lines.push(`  ${gearName} Gear: ${ratio.toFixed(2)}`);
      });
    }

    lines.push(``);
    lines.push(`▸ ALIGNMENT`);
    lines.push(`  Camber Front: ${tune.camberFront}°`);
    lines.push(`  Camber Rear: ${tune.camberRear}°`);
    lines.push(`  Toe Front: ${tune.toeFront}°`);
    lines.push(`  Toe Rear: ${tune.toeRear}°`);
    lines.push(`  Caster: ${tune.caster}°`);
    lines.push(``);
    lines.push(`▸ ANTI-ROLL BARS`);
    lines.push(`  Front: ${tune.arbFront}`);
    lines.push(`  Rear: ${tune.arbRear}`);
    lines.push(``);
    lines.push(`▸ SPRINGS`);
    lines.push(`  Front: ${displayTune.springsFront} ${units.springs}`);
    lines.push(`  Rear: ${displayTune.springsRear} ${units.springs}`);
    lines.push(`  Ride Height Front: ${displayTune.rideHeightFront} ${units.rideHeight}`);
    lines.push(`  Ride Height Rear: ${displayTune.rideHeightRear} ${units.rideHeight}`);
    lines.push(``);
    lines.push(`▸ DAMPING`);
    lines.push(`  Rebound Front: ${tune.reboundFront}`);
    lines.push(`  Rebound Rear: ${tune.reboundRear}`);
    lines.push(`  Bump Front: ${tune.bumpFront}`);
    lines.push(`  Bump Rear: ${tune.bumpRear}`);
    lines.push(``);
    lines.push(`▸ AERO`);
    lines.push(`  Front: ${displayTune.aeroFront} ${units.aero}`);
    lines.push(`  Rear: ${displayTune.aeroRear} ${units.aero}`);
    lines.push(``);
    lines.push(`▸ BRAKES`);
    lines.push(`  Pressure: ${tune.brakePressure}%`);
    lines.push(`  Balance: ${tune.brakeBalance}%`);
    lines.push(``);
    lines.push(`▸ DIFFERENTIAL`);

    if (driveType === 'AWD') {
      lines.push(`  Center Balance: ${tune.centerBalance || 50}% Rear`);
      if (tune.diffAccelFront !== undefined) {
        lines.push(`  Front Accel: ${tune.diffAccelFront}%`);
        lines.push(`  Front Decel: ${tune.diffDecelFront || 0}%`);
      }
    }
    if (driveType !== 'FWD') {
      lines.push(`  Rear Accel: ${tune.diffAccelRear}%`);
      lines.push(`  Rear Decel: ${tune.diffDecelRear}%`);
    }
    if (driveType === 'FWD') {
      lines.push(`  Front Accel: ${tune.diffAccelFront}%`);
      lines.push(`  Front Decel: ${tune.diffDecelFront || 0}%`);
    }

    lines.push(``);
    lines.push(`═══════════════════════════════════`);
    lines.push(`Generated by Forza Tuning Calculator`);
    lines.push(`═══════════════════════════════════`);

    return lines.join('\n');
  };

  const handleCopyAll = async () => {
    try {
      await navigator.clipboard.writeText(formatTuneForClipboard());
      setCopied(true);
      toast.success('Tune copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error('Failed to copy tune');
    }
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="module-block p-4 flex items-center justify-between">
        <div>
          <h2 className="font-display text-lg text-foreground flex items-center gap-2">
            <span className="text-gradient-neon">{carName || 'Custom Car'}</span>
          </h2>
          <div className="flex items-center gap-2 mt-1">
            <span 
              className="text-xs font-mono uppercase px-2 py-0.5 rounded"
              style={{
                background: 'hsl(var(--neon-pink) / 0.15)',
                color: 'hsl(var(--neon-pink))',
                border: '1px solid hsl(var(--neon-pink) / 0.3)',
              }}
            >
              {tuneInfo.title}
            </span>
            <span 
              className="text-xs font-mono uppercase px-2 py-0.5 rounded"
              style={{
                background: 'hsl(var(--neon-cyan) / 0.15)',
                color: 'hsl(var(--neon-cyan))',
                border: '1px solid hsl(var(--neon-cyan) / 0.3)',
              }}
            >
              {driveType}
            </span>
          </div>
        </div>
        
        <Button
          onClick={handleCopyAll}
          className={cn(
            "gap-2 transition-all",
            copied 
              ? "bg-module-suspension text-white" 
              : "bg-neon-pink/20 text-neon-pink border border-neon-pink/30 hover:bg-neon-pink/30"
          )}
        >
          {copied ? (
            <>
              <Check className="w-4 h-4" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="w-4 h-4" />
              Copy All
            </>
          )}
        </Button>
      </div>

      {/* Modular Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Tires Module */}
        <TuningModule
          id="tires"
          title="Tires"
          category="tires"
          icon={<Gauge className="w-4 h-4" />}
          isDragging={draggedModule === 'tires'}
          onDragStart={setDraggedModule}
          onDragEnd={() => setDraggedModule(null)}
        >
          <div className="space-y-1">
            <BlueprintSlider
              label="Front Pressure"
              value={displayTune.tirePressureFront}
              min={unitSystem === 'imperial' ? 14 : 0.96}
              max={unitSystem === 'imperial' ? 35 : 2.41}
              unit={units.pressure}
              leftLabel="Soft"
              rightLabel="Hard"
              category="tires"
              explanationKey="tirePressureFront"
            />
            <BlueprintSlider
              label="Rear Pressure"
              value={displayTune.tirePressureRear}
              min={unitSystem === 'imperial' ? 14 : 0.96}
              max={unitSystem === 'imperial' ? 35 : 2.41}
              unit={units.pressure}
              leftLabel="Soft"
              rightLabel="Hard"
              category="tires"
              explanationKey="tirePressureRear"
            />
          </div>
        </TuningModule>

        {/* Gearing Module */}
        <TuningModule
          id="gearing"
          title="Gearing"
          category="gearing"
          icon={<Cog className="w-4 h-4" />}
          isDragging={draggedModule === 'gearing'}
          onDragStart={setDraggedModule}
          onDragEnd={() => setDraggedModule(null)}
        >
          <div className="space-y-3">
            <BlueprintSlider
              label="Final Drive"
              value={tune.finalDrive}
              min={2.0}
              max={6.0}
              isHighlighted
              category="gearing"
              explanationKey="finalDrive"
            />
            <div className="grid grid-cols-3 gap-1.5">
              {tune.gearRatios.map((ratio, i) => (
                <CompactValue
                  key={i}
                  label={i === 0 ? '1st' : i === 1 ? '2nd' : i === 2 ? '3rd' : `${i + 1}th`}
                  value={ratio.toFixed(2)}
                  category="gearing"
                  size="sm"
                />
              ))}
            </div>
          </div>
        </TuningModule>

        {/* Alignment Module */}
        <TuningModule
          id="alignment"
          title="Alignment"
          category="alignment"
          icon={<Compass className="w-4 h-4" />}
          isDragging={draggedModule === 'alignment'}
          onDragStart={setDraggedModule}
          onDragEnd={() => setDraggedModule(null)}
        >
          <div className="space-y-3">
            <FrontRearValue
              label="Camber"
              front={tune.camberFront}
              rear={tune.camberRear}
              unit="°"
              category="alignment"
            />
            <FrontRearValue
              label="Toe"
              front={tune.toeFront}
              rear={tune.toeRear}
              unit="°"
              category="alignment"
            />
            <CompactValue
              label="Caster"
              value={tune.caster}
              unit="°"
              category="alignment"
            />
          </div>
        </TuningModule>

        {/* Anti-Roll Bars Module */}
        <TuningModule
          id="antiroll"
          title="Anti-Roll Bars"
          category="suspension"
          icon={<Settings2 className="w-4 h-4" />}
          isDragging={draggedModule === 'antiroll'}
          onDragStart={setDraggedModule}
          onDragEnd={() => setDraggedModule(null)}
        >
          <div className="space-y-1">
            <BlueprintSlider
              label="Front ARB"
              value={tune.arbFront}
              min={1}
              max={65}
              leftLabel="Soft"
              rightLabel="Stiff"
              category="suspension"
              explanationKey="arbFront"
            />
            <BlueprintSlider
              label="Rear ARB"
              value={tune.arbRear}
              min={1}
              max={65}
              leftLabel="Soft"
              rightLabel="Stiff"
              category="suspension"
              explanationKey="arbRear"
            />
          </div>
        </TuningModule>

        {/* Springs Module */}
        <TuningModule
          id="springs"
          title="Springs"
          category="suspension"
          icon={<Activity className="w-4 h-4" />}
          isDragging={draggedModule === 'springs'}
          onDragStart={setDraggedModule}
          onDragEnd={() => setDraggedModule(null)}
        >
          <div className="space-y-3">
            <div className="space-y-1">
              <BlueprintSlider
                label="Front Springs"
                value={displayTune.springsFront}
                min={unitSystem === 'imperial' ? 100 : 1.79}
                max={unitSystem === 'imperial' ? 1000 : 17.86}
                unit={units.springs}
                leftLabel="Soft"
                rightLabel="Stiff"
                category="suspension"
                explanationKey="springsFront"
              />
              <BlueprintSlider
                label="Rear Springs"
                value={displayTune.springsRear}
                min={unitSystem === 'imperial' ? 100 : 1.79}
                max={unitSystem === 'imperial' ? 1000 : 17.86}
                unit={units.springs}
                leftLabel="Soft"
                rightLabel="Stiff"
                category="suspension"
                explanationKey="springsRear"
              />
            </div>
            <FrontRearValue
              label="Ride Height"
              front={displayTune.rideHeightFront}
              rear={displayTune.rideHeightRear}
              unit={units.rideHeight}
              category="suspension"
            />
          </div>
        </TuningModule>

        {/* Damping Module */}
        <TuningModule
          id="damping"
          title="Damping"
          category="damping"
          icon={<Wrench className="w-4 h-4" />}
          isDragging={draggedModule === 'damping'}
          onDragStart={setDraggedModule}
          onDragEnd={() => setDraggedModule(null)}
        >
          <div className="space-y-3">
            <FrontRearValue
              label="Rebound"
              front={tune.reboundFront}
              rear={tune.reboundRear}
              category="damping"
            />
            <FrontRearValue
              label="Bump"
              front={tune.bumpFront}
              rear={tune.bumpRear}
              category="damping"
            />
          </div>
        </TuningModule>

        {/* Aero Module */}
        <TuningModule
          id="aero"
          title="Aero"
          category="aero"
          icon={<Wind className="w-4 h-4" />}
          isDragging={draggedModule === 'aero'}
          onDragStart={setDraggedModule}
          onDragEnd={() => setDraggedModule(null)}
        >
          <div className="space-y-1">
            <BlueprintSlider
              label="Front Downforce"
              value={displayTune.aeroFront}
              min={0}
              max={unitSystem === 'imperial' ? 400 : 1779}
              unit={units.aero}
              leftLabel="Low"
              rightLabel="High"
              category="aero"
              explanationKey="aeroFront"
            />
            <BlueprintSlider
              label="Rear Downforce"
              value={displayTune.aeroRear}
              min={0}
              max={unitSystem === 'imperial' ? 400 : 1779}
              unit={units.aero}
              leftLabel="Low"
              rightLabel="High"
              category="aero"
              explanationKey="aeroRear"
            />
          </div>
        </TuningModule>

        {/* Brakes Module */}
        <TuningModule
          id="brakes"
          title="Brakes"
          category="brakes"
          icon={<Disc className="w-4 h-4" />}
          isDragging={draggedModule === 'brakes'}
          onDragStart={setDraggedModule}
          onDragEnd={() => setDraggedModule(null)}
        >
          <div className="space-y-1">
            <BlueprintSlider
              label="Pressure"
              value={tune.brakePressure}
              min={50}
              max={200}
              unit="%"
              leftLabel="Light"
              rightLabel="Heavy"
              category="brakes"
              explanationKey="brakePressure"
            />
            <BlueprintSlider
              label="Balance"
              value={tune.brakeBalance}
              min={40}
              max={60}
              unit="%"
              leftLabel="Rear"
              rightLabel="Front"
              category="brakes"
              explanationKey="brakeBalance"
            />
          </div>
        </TuningModule>

        {/* Differential Module */}
        <TuningModule
          id="differential"
          title="Differential"
          category="differential"
          icon={<Settings2 className="w-4 h-4" />}
          isDragging={draggedModule === 'differential'}
          onDragStart={setDraggedModule}
          onDragEnd={() => setDraggedModule(null)}
          className="md:col-span-2"
        >
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {driveType === 'AWD' && (
              <div>
                <CompactValue
                  label="Center Balance"
                  value={`${tune.centerBalance || 50}%`}
                  category="differential"
                />
                <p className="text-[10px] text-muted-foreground/60 mt-1 font-sketch">
                  → Power to rear
                </p>
              </div>
            )}
            
            {(driveType === 'AWD' || driveType === 'FWD') && (
              <FrontRearValue
                label="Front Diff"
                front={tune.diffAccelFront || 0}
                rear={tune.diffDecelFront || 0}
                unit="%"
                category="differential"
              />
            )}
            
            {(driveType === 'AWD' || driveType === 'RWD') && (
              <FrontRearValue
                label="Rear Diff"
                front={tune.diffAccelRear}
                rear={tune.diffDecelRear}
                unit="%"
                category="differential"
              />
            )}
          </div>
        </TuningModule>
      </div>

      {/* Tune Tips */}
      <div 
        className="module-block p-4"
        style={{
          borderLeft: '3px solid hsl(var(--neon-cyan))',
        }}
      >
        <h3 className="font-sketch text-lg text-neon-cyan mb-2">
          {tuneInfo.title} Tune Tips
        </h3>
        <p className="text-sm text-muted-foreground font-body">
          {tuneType === 'grip' && 'Focus on maximizing mechanical grip through balanced suspension and optimal tire temperatures. Keep ARBs relatively stiff for quick transitions.'}
          {tuneType === 'drift' && 'Maximize rear wheel slip while maintaining control. Softer front suspension and stiffer rear helps initiate and hold angles.'}
          {tuneType === 'drag' && 'All about traction and straight-line stability. Lower rear for grip, minimize rolling resistance.'}
          {tuneType === 'offroad' && 'Prioritize suspension travel and stability over bumpy terrain. Softer settings overall with higher ride height.'}
          {tuneType === 'rally' && 'Balance between grip and controlled slides. Medium-soft suspension for absorbing impacts while maintaining cornering ability.'}
          {tuneType === 'street' && 'Versatile tune for mixed conditions. Balanced settings that work on various surfaces and driving styles.'}
        </p>
      </div>
    </div>
  );
};
